"""
    MILP

Represent a Mixed Integer Linear Program in "cuPDLPx form":

    min cᵀx + c0   s.t.   lv ≤ x ≤ uv
                          lc ≤ A * x ≤ uc

A `MILP` can also hold a whole batch of such programs sharing the constraint matrix `A`: any
of `c`, `lv`, `uv`, `lc` and `uc` may then be a matrix with one column per instance, while
the others stay vectors shared by the whole batch. All batched fields must agree on the
number of instances; see [`isbatched`](@ref) and [`nbinstances`](@ref). The objective constant
`c0` is always a single number, shared by the whole batch.

# Constructor

    MILP(;
        c, lv, uv, A, lc, uc,
        At=sametype_transpose(A),
        [c0, D1, D2, int_var, var_names, con_names, dataset, name, path]
    )

# Fields

$(TYPEDFIELDS)
"""
struct MILP{
        T <: Number,
        Vo <: AbstractVecOrMat{T},
        Vlv <: AbstractVecOrMat{T},
        Vuv <: AbstractVecOrMat{T},
        Vlc <: AbstractVecOrMat{T},
        Vuc <: AbstractVecOrMat{T},
        Dg1 <: Diagonal{T},
        Dg2 <: Diagonal{T},
        M <: AbstractMatrix{T},
        Mt <: AbstractMatrix{T},
        Vb <: DenseVector,
        Tc <: Number,
    }
    "objective vector"
    c::Vo
    "objective constant, of its own type parameter so that Reactant can trace it as a number"
    c0::Tc
    "variable lower bound"
    lv::Vlv
    "variable upper bound"
    uv::Vuv
    "constraint matrix"
    A::M
    "transposed constraint matrix"
    At::Mt
    "constraint lower bound"
    lc::Vlc
    "constraint upper bound"
    uc::Vuc
    "left preconditioner"
    D1::Dg1
    "right preconditioner"
    D2::Dg2
    "which variables must be integers"
    int_var::Vb
    "variable names"
    var_names::Vector{String}
    "constraint names"
    con_names::Vector{String}
    "source dataset"
    dataset::String
    "instance name (last part of the path)"
    name::String
    "file path the MILP was read from"
    path::String

    function MILP(;
            c,
            c0 = false,
            lv,
            uv,
            A,
            At = sametype_transpose(A),
            lc,
            uc,
            D1 = Diagonal(one!(similar(lc, size(lc, 1)))),
            D2 = Diagonal(one!(similar(lv, size(lv, 1)))),
            int_var = zero!(similar(c, Bool, size(c, 1))),
            var_names = map(string, axes(c, 1)),
            con_names = map(string, axes(lc, 1)),
            dataset = "",
            name = "",
            path = ""
        )
        m, n = size(A)
        if !(n == size(c, 1) == size(lv, 1) == size(uv, 1) == size(D2, 1) == length(int_var) == length(var_names))
            throw(DimensionMismatch("Variable size not consistent"))
        elseif !(m == size(lc, 1) == size(uc, 1) == size(D1, 2) == length(con_names))
            throw(DimensionMismatch("Constraint size not consistent"))
            # whatever is batched must agree on the number of instances
        elseif !allequal(Iterators.filter(!isone, batch_sizes(c, lv, uv, lc, uc)))
            throw(DimensionMismatch("Batch size not consistent"))
        end

        # batching mixes container types (a shared bound is a vector next to a batched
        # matrix), so only the element type and the backend can be required to match
        numbers = (c, lv, uv, A, At, lc, uc, D1, D2)
        T = Base.promote_eltype(numbers...)
        if !isconcretetype(T)
            throw(ArgumentError("Abstract element type $T"))
        elseif !all(x -> eltype(x) === T, numbers)
            throw(ArgumentError("Element type not consistent: $(map(eltype, numbers))"))
        end

        common_backend(numbers...)

        if isempty(name) && !isempty(path)
            name = splitext(splitpath(path)[end])[1]
        end

        return new{
            T, typeof(c), typeof(lv), typeof(uv), typeof(lc), typeof(uc),
            typeof(D1), typeof(D2), typeof(A), typeof(At), typeof(int_var), T,
        }(
            c,
            convert(T, c0),
            lv,
            uv,
            A,
            At,
            lc,
            uc,
            D1,
            D2,
            int_var,
            var_names,
            con_names,
            string(dataset),
            string(name),
            string(path)
        )
    end
end

"""
    MILP(qps::QPSData; kwargs...)

Construct a [`MILP`](@ref) from a `QPSData` object generated by [QPSReader.jl](https://github.com/JuliaSmoothOptimizers/QPSReader.jl).

A [`MILP`](@ref) is always a minimization problem, so a maximization problem `max cᵀx + c0` is
stored as the equivalent `min -cᵀx - c0`, whose optimal value is the opposite of the original one.
"""
function MILP(qps::QPSData; kwargs...)
    c, c0 = if qps.objsense == :max
        -qps.c, -qps.c0  # switch objective for minimization
    else  # qps.objsense in (:min, :notset)
        qps.c, qps.c0  # keep objective for minimization
    end
    return MILP(;
        c = c,
        c0 = c0,
        lv = qps.lvar,
        uv = qps.uvar,
        A = sparse(qps.arows, qps.acols, qps.avals, length(qps.lcon), length(qps.lvar)),
        At = sparse(qps.acols, qps.arows, qps.avals, length(qps.lvar), length(qps.lcon)),
        lc = qps.lcon,
        uc = qps.ucon,
        D1 = Diagonal(ones(length(qps.lcon))),
        D2 = Diagonal(ones(length(qps.lvar))),
        int_var = convert(Vector{Bool}, (qps.vartypes .== VTYPE_Binary) .| (qps.vartypes .== VTYPE_Integer)),
        var_names = qps.varnames,
        con_names = qps.connames,
        kwargs...
    )
end

function Base.show(
        io::IO, milp::MILP{T, Vo, Vlv, Vuv, Vlc, Vuc, Dg1, Dg2, M, Mt}
    ) where {T, Vo, Vlv, Vuv, Vlc, Vuc, Dg1, Dg2, M, Mt}
    vectors = unique((Vo, Vlv, Vuv, Vlc, Vuc))
    print(
        io, """
        $(isbatched(milp) ? "Batched " : "")MILP instance $(milp.name) from dataset $(milp.dataset):
        - types:
          - values $T
          - vectors $(length(vectors) == 1 ? only(vectors) : Tuple(vectors))
          - matrices $(M == Mt ? M : (M, Mt))
        - variables: $(nbvar(milp))
          - $(nbvar_cont(milp)) continuous
          - $(nbvar_int(milp)) integer
        - constraints: $(nbcons(milp))"""
    )
    if ndims(milp.lc) == 1
        print(io, "\n  - $(nbcons_ineq(milp)) inequalities")
        print(io, "\n  - $(nbcons_eq(milp)) equalities")
    end
    print(io, "\n- nonzeros: $(mynnz(milp.A))")
    if isbatched(milp)
        print(io, "\n- batch size: $(nbinstances(milp))")
    end
    return nothing
end

KernelAbstractions.get_backend(milp::MILP) = get_backend(milp.c)

"""
    nbvar(milp)

Return the number of variables in `milp`.
"""
nbvar(milp::MILP) = size(milp.c, 1)

"""
    nbvar_int(milp)

Return the number of integer variables in `milp`.
"""
nbvar_int(milp::MILP) = sum(identity, milp.int_var)

"""
    nbvar_cont(milp)

Return the number of continuous variables in `milp`.
"""
nbvar_cont(milp::MILP) = sum(!, milp.int_var)

"""
    nbcons(milp)

Return the number of constraints in `milp`, not including variable bounds or integrality requirements.
"""
nbcons(milp::MILP) = size(milp.A, 1)

"""
    nbcons_eq(milp)

Return the number of equality constraints in `milp`.

Throw an `ArgumentError` if the constraint bounds of `milp` are batched, since the number may then differ from one instance to the next.
"""
function nbcons_eq(milp::MILP)
    if ndims(milp.lc) > 1
        throw(
            ArgumentError(
                "Cannot count equality constraints with batched constraint bounds, pick a single instance first"
            )
        )
    end
    return mapreduce(==, +, milp.lc, milp.uc)
end

"""
    nbcons_ineq(milp)

Return the number of inequality constraints in `milp`, not including variable bounds.
"""
nbcons_ineq(milp::MILP) = nbcons(milp) - nbcons_eq(milp)

function Base.isapprox(m1::MILP, m2::MILP; kwargs...)
    return (
        isapprox(m1.c, m2.c; kwargs...) &&
            isapprox(m1.c0, m2.c0; kwargs...) &&
            isapprox(m1.lv, m2.lv; kwargs...) &&
            isapprox(m1.uv, m2.uv; kwargs...) &&
            isapprox(m1.A, m2.A; kwargs...) &&
            isapprox(m1.At, m2.At; kwargs...) &&
            isapprox(m1.lc, m2.lc; kwargs...) &&
            isapprox(m1.uc, m2.uc; kwargs...) &&
            isapprox(m1.D1, m2.D1; kwargs...) &&
            isapprox(m1.D2, m2.D2; kwargs...) &&
            m1.int_var == m2.int_var &&
            m1.var_names == m2.var_names &&
            m1.con_names == m2.con_names &&
            m1.dataset == m2.dataset &&
            m1.name == m2.name &&
            m1.path == m2.path
    )
end

"""
    batch_sizes(c, lv, uv, lc, uc)

Return the number of instances carried by each field of a [`MILP`](@ref) which can be batched, `1` meaning shared by the whole batch.
"""
function batch_sizes(c, lv, uv, lc, uc)
    return (size(c, 2), size(lv, 2), size(uv, 2), size(lc, 2), size(uc, 2))
end

function nbinstances((; c, lv, uv, lc, uc)::MILP)
    return maximum(batch_sizes(c, lv, uv, lc, uc))
end

"""
    isbatched(milp)

Return whether `milp` holds a batch of instances rather than a single one.

Unlike [`nbinstances`](@ref), this only depends on the type of `milp`, so it is a constant as
far as inference is concerned and the shape of the arrays attached to `milp` follows from it.
"""
function isbatched((; c, lv, uv, lc, uc)::MILP)
    return ndims(c) > 1 || ndims(lv) > 1 || ndims(uv) > 1 || ndims(lc) > 1 || ndims(uc) > 1
end
function instance(milp::MILP, i::Int)
    return MILP(;
        c = instance_vec(milp.c, i),
        c0 = milp.c0,
        lv = instance_vec(milp.lv, i),
        uv = instance_vec(milp.uv, i),
        A = milp.A,
        At = milp.At,
        lc = instance_vec(milp.lc, i),
        uc = instance_vec(milp.uc, i),
        D1 = milp.D1,
        D2 = milp.D2,
        int_var = milp.int_var,
        var_names = milp.var_names,
        con_names = milp.con_names,
        dataset = milp.dataset,
        name = milp.name,
        path = milp.path
    )
end
